version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password is set here
      MYSQL_DATABASE: dbname
    volumes:
      - ./app:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db_container  # Custom container name for the db service

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db_container  # Connects to the db service
      MYSQL_USER: root  # Use root user
      MYSQL_PASSWORD: rootpassword  # Use root password set in db service
      MYSQL_DB: dbname
      SECRET_KEY: your_secret_key
    container_name: app_container

volumes:
  db-data: