version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
    volumes:
      - ./app:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db_container

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db_container
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: dbname
      SECRET_KEY: your_secret_key
    container_name: app_container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_container
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    container_name: phpmyadmin_container

volumes:
  dbdata: